#!/bin/bash

# Script Name: fit

# paths
export repo_path=".fit/repo"
export worktrees_path=".fit/worktrees"

# subscripts
subscript_path="$HOME/bin/fit-bin"
source $subscript_path/add
source $subscript_path/branch
source $subscript_path/cd_root
source $subscript_path/clone
source $subscript_path/colorize
source $subscript_path/commit
source $subscript_path/init
source $subscript_path/list
source $subscript_path/status
source $subscript_path/status

# Main logic for script
case $1 in
	init)
		init $2
		;;
	clone)
		clone $2 $3
		;;
	branch)
		branch $2
		;;
	list)
		list
		;;
	status)
		status
		;;
	add)
		add $2 $3
		;;
	commit)
		commit $2 "$3"
		;;
	*)
		echo "Error: Unknown command '$1'."
		echo "Usage: fit {clone|branch|status|add|commit}"
		exit 1
		;;
esac
